spring:
  redis:
    host: redis-9b72efef-ea1b-4792-9fe3-04243136a67e.cn-east-3.dcs.myhuaweicloud.com
    port: 6379
    #password: 123456
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: HEXZX2659
    url: jdbc:mysql://127.0.0.1:3306/books?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    type: com.alibaba.druid.pool.DruidDataSource
swagger.show: true